# Generated by Django 5.1.4 on 2024-12-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('job_type', models.CharField(choices=[('hybrid', 'Hybrid'), ('remote', 'Remote'), ('office', 'Office')], max_length=10)),
                ('description', models.TextField()),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skills_required', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
