# Generated by Django 5.1.4 on 2025-01-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_profile_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='currenct',
            field=models.CharField(choices=[('Теңге', 'Tenge'), ('Доллар', 'Dollar'), ('Евро', 'Euro')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('hybrid', 'Hybrid'), ('remote', 'Remote'), ('office', 'Office'), ('full-time', 'Full-Time')], max_length=10),
        ),
    ]
