# Generated by Django 5.1.4 on 2025-01-11 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_job_currenct_alter_job_job_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='currenct',
            new_name='currency',
        ),
    ]
